force-app/main/default/objects/Positions__c/Positions__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Position</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Positions__c/fields/Close_Position__c.field-meta.xml
<CustomField>
    <fullName>Close_Position__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Close Position</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ClosePositionScheduler.cls
global class ClosePositionScheduler implements Schedulable {
    global void execute(SchedulableContext sc){
        List<Positions__c> positionToClose = [SELECT 
                                                   Id,
                                                   Close_Position__c 
                                             FROM Positions__c 
                                             WHERE Close_Position__c = false 
                                             AND CreatedDate = LAST_N_DAYS:30];
        
        for(Positions__c position:positionToClose){
            position.Close_Position__c =true;
        }
        update positionToClose;
    }

}